controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6
  - name: fake_right_arm_controller
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6
  - name: fake_left_hand_controller
    joints:
      - left_hand_j0
      - left_hand_j1
      - left_hand_j2
      - left_hand_j3
      - left_hand_j4
  - name: fake_right_hand_controller
    joints:
      - right_hand_j0
      - right_hand_j1
      - right_hand_j2
      - right_hand_j3
      - right_hand_j4