

footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]] #Se puede aumentar para mayor seguridad
footprint_padding: 0.01

#robot_radius: 0.25

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

unknown_cost_value : 255

resolution: 0.05

raytrace_range: 5.5
obstacle_range: 5.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, min_obstacle_height: -0.1, max_obstacle_height: 0.2, expected_update_rate: 0.3, observation_persistence: 1.0}

inflation:
    cost_scaling_factor: 2.0 #Antes era 10 y ajustaba demasiado a obstaculos
    inflation_radius: 0.55 #Esta es la que hay que modificar en caso de seguridad. Antes 0.45
    enabled: true

footprint_layer:
    enabled: true
